version: '3'

networks: 
    pubsub-net:
        driver: bridge

services:
    mosquitto1:
        image: eclipse-mosquitto:latest
        container_name: broker1
        ports:
            - 1883:1883
        volumes:
            - ./mosquitto:/mosquitto/
        networks: 
            - pubsub-net
